scrape_configs:
  - job_name: 'lab-spring-prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      #      - targets: [ 'host.docker.internal:8080' ]
      - targets: [ 'spring-app:8080' ]
        labels:
          namespace: czetsuyatech
          application: 'lab-spring-prometheus'
